# Generated by Django 2.1.1 on 2018-09-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users_profils',
            new_name='users_profiles',
        ),
    ]
