# Generated by Django 2.1.1 on 2018-09-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteeApp', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='input_quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Name of the sender', max_length=500)),
                ('sayer', models.EmailField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
