# Generated by Django 2.1.1 on 2018-09-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteeApp', '0012_auto_20180930_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_quote',
            name='picture_ME',
        ),
        migrations.AddField(
            model_name='input_quote',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
