# Generated by Django 2.1.1 on 2018-09-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteeApp', '0013_auto_20180930_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_quote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
